# permissions for end users to edit gitsyncs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitsync-editor-role
rules:
- apiGroups:
  - api.adityajoshi.online
  resources:
  - gitsyncs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - api.adityajoshi.online
  resources:
  - gitsyncs/status
  verbs:
  - get
