# permissions for end users to view gitsyncs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitsync-viewer-role
rules:
- apiGroups:
  - api.adityajoshi.online
  resources:
  - gitsyncs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - api.adityajoshi.online
  resources:
  - gitsyncs/status
  verbs:
  - get
